# Generated by Django 2.0.7 on 2018-07-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0001_initial'),
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empaquetado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='playeras',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vender.Cliente'),
        ),
        migrations.AddField(
            model_name='playeras',
            name='tipo',
            field=models.ManyToManyField(to='almacen.Empaquetado'),
        ),
    ]
