# Generated by Django 2.0.7 on 2018-07-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_auto_20180717_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empaquetado',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
