# Generated by Django 2.0.7 on 2018-07-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20180718_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empaquetado',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
